### ISSUE TITLE
OC引导界面显示问题

### ISSUE THREAD

**Issue by 71coder** [ParrotXray/GA-B85M-D3H-Haswell-Hackintosh#3]
OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？

**Comment by 71coder** [comment]
我使用的是4k屏幕

**Comment by ParrotXray** [comment]
你試試看這樣
下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip，刪掉原本的Resources，把新的放上

**Comment by ParrotXray** [comment]
> OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？

你試試看這樣
下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip
刪掉原本的Resources，把新的放上

**Comment by 71coder** [comment]
> > OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？
> 
> 你試試看這樣 下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip 刪掉原本的Resources，把新的放上

我大概是找到原因了，和主题并没有关系。是我电脑在bios和引导界面是分辨率都只有1024x768，并没有输出屏幕的4k分辨率。显卡的gop也更新过了，现在bios的版本是f14还是f15的，不知道和bios版本有没有关系。你的显示器是否是4k的，是否有遇到这个问题呢，能否分享你的bios

**Comment by ParrotXray** [comment]
> > > OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？
> > 
> > 
> > 你試試看這樣 下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip 刪掉原本的Resources，把新的放上
> 
> 我大概是找到原因了，和主题并没有关系。是我电脑在bios和引导界面是分辨率都只有1024x768，并没有输出屏幕的4k分辨率。显卡的gop也更新过了，现在bios的版本是f14还是f15的，不知道和bios版本有没有关系。你的显示器是否是4k的，是否有遇到这个问题呢，能否分享你的bios

我使用的屏幕是只有1080的，所以不清楚4k屏以及在開啟hidpi的狀況，我覺得可以檢查CSM有沒有關閉，那個好像會影響分辨率。至於bios的部分，我是使用f12版的，因為在之前的測試只有f12的能上Ventura後幾版的都會卡代碼。

**Comment by 71coder** [comment]
> > > > OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？
> > > 
> > > 
> > > 你試試看這樣 下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip 刪掉原本的Resources，把新的放上
> > 
> > 
> > 我大概是找到原因了，和主题并没有关系。是我电脑在bios和引导界面是分辨率都只有1024x768，并没有输出屏幕的4k分辨率。显卡的gop也更新过了，现在bios的版本是f14还是f15的，不知道和bios版本有没有关系。你的显示器是否是4k的，是否有遇到这个问题呢，能否分享你的bios
> 
> 我使用的屏幕是只有1080的，所以不清楚4k屏以及在開啟hidpi的狀況，我覺得可以檢查CSM有沒有關閉，那個好像會影響分辨率。至於bios的部分，我是使用f12版的，因為在之前的測試只有f12的能上Ventura後幾版的都會卡代碼。

如果操作系统类型选择其他操作系统的话，好像会自动开启CSM，并且没有CSM开关可以让我关闭它，如果选择win8则有独立CSM开关，但我有尝试过选择win8然后关闭CSM，不过不起作用。另外我使用f15的bios可以安装Ventura，最初安装有报错，但当我将SMBIOS机型改为MacPro7.1后就可以正常安装了

**Comment by ParrotXray** [comment]
> > > > > OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？
> > > > 
> > > > 
> > > > 你試試看這樣 下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip 刪掉原本的Resources，把新的放上
> > > 
> > > 
> > > 我大概是找到原因了，和主题并没有关系。是我电脑在bios和引导界面是分辨率都只有1024x768，并没有输出屏幕的4k分辨率。显卡的gop也更新过了，现在bios的版本是f14还是f15的，不知道和bios版本有没有关系。你的显示器是否是4k的，是否有遇到这个问题呢，能否分享你的bios
> > 
> > 
> > 我使用的屏幕是只有1080的，所以不清楚4k屏以及在開啟hidpi的狀況，我覺得可以檢查CSM有沒有關閉，那個好像會影響分辨率。至於bios的部分，我是使用f12版的，因為在之前的測試只有f12的能上Ventura後幾版的都會卡代碼。
> 
> 如果操作系统类型选择其他操作系统的话，好像会自动开启CSM，并且没有CSM开关可以让我关闭它，如果选择win8则有独立CSM开关，但我有尝试过选择win8然后关闭CSM，不过不起作用。另外我使用f15的bios可以安装Ventura，最初安装有报错，但当我将SMBIOS机型改为MacPro7.1后就可以正常安装

**Comment by ParrotXray** [comment]
> > > > > > OC引导界面图标变形、模糊，然后我将nvram里的uiscale改为02的话，引导界面会变为文字引导，而改回01就会有主题展示但是图标变形模糊，此问题该如何解决呢？
> > > > > 
> > > > > 
> > > > > 你試試看這樣 下載這個：https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip 刪掉原本的Resources，把新的放上
> > > > 
> > > > 
> > > > 我大概是找到原因了，和主题并没有关系。是我电脑在bios和引导界面是分辨率都只有1024x768，并没有输出屏幕的4k分辨率。显卡的gop也更新过了，现在bios的版本是f14还是f15的，不知道和bios版本有没有关系。你的显示器是否是4k的，是否有遇到这个问题呢，能否分享你的bios
> > > 
> > > 
> > > 我使用的屏幕是只有1080的，所以不清楚4k屏以及在開啟hidpi的狀況，我覺得可以檢查CSM有沒有關閉，那個好像會影響分辨率。至於bios的部分，我是使用f12版的，因為在之前的測試只有f12的能上Ventura後幾版的都會卡代碼。
> > 
> > 
> > 如果操作系统类型选择其他操作系统的话，好像会自动开启CSM，并且没有CSM开关可以让我关闭它，如果选择win8则有独立CSM开关，但我有尝试过选择win8然后关闭CSM，不过不起作用。另外我使用f15的bios可以安装Ventura，最初安装有报错，但当我将SMBIOS机型改为MacPro7.1后就可以正常安装

可能OC更新後f15就可以了，因為當時測試時Ventura還是測試版
