### ISSUE TITLE
安装卡白苹果问题

### ISSUE THREAD

**Issue by Znano5696** [ParrotXray/GA-B85M-D3H-Haswell-Hackintosh#4]
请大佬帮忙看看
使用最新OC0.9.0，安装Mac OS 13.3 Ventura-做如下安装测试：

本人配置： B85M D3H (rev1.2版本) - E3-1231V3 - BCM943602CS - RX580
1.Bois刷回F12版本，但启动进入Bois未发现CFG Lock, 无法设置关闭； 其他Bios参数已经按照提示设置好。

2.直接使用解压的EFI, 删除EFI/OC/ACPI内的文件，使用B85M-D3H ACPI文件，OC启用，设备型号OC中联网选择MacPro7.1，保存，安装时卡在【MacOS Ventura将安装在磁盘“OS”上----剩余大约12分钟】左右卡死重启。

3.直接使用解压的EFI, 未使用B85M-D3H ACPI内容，设备型号OC中联网选择MacPro7.1， 安装时亦卡在【MacOS Ventura将安装在磁盘“OS”上----剩余大约12分钟】左右卡死重启。

EFI引导提示：

#【EB.LD.LF|IND】(“(null string)"> ("1*)
#【CEB.B.SBS|SZ】 723512
#【CEB|B:SHA 】(Gaaf054766771d2h08ff011eb600c90c161d9285)
#【LEB.WL.PWLFNV11】 Err (0xE) <- RT.GV wake-fallure 7C436110-AB2R-4BBB-ABBO-FE41995C9FB2
#【CEB.ML.DTI11 Err(0xE) <- EB.WL.PWLFNV
#【CEB.WL.PWLFRTC I NONE1
#【LEB.WL.DTI1】 Err(OxE) <- EB.WL.PULFRTC
#【EB.LD.LKCID]】("System)LibraryWernelCollections\BootKernelExtensions.kc.development">
#【HEB.LD.OFS|OPEN1】 Err (®xE) ("System) WLibrary) VernelCollections\ \BootKernelExtensions.kc.development">
#【EB.LD.LKCIR.2】 ("System\Llbrary\ KernelCollections\BootKernelExtensions.kc">
xxxxx
-----之后滚条进入安装界面

安装日志错误提示(剩余大约12分钟卡死重启前的提示)：
-------xxx   Syncing extracted data to disk

请问一下，我是不是哪里配置出错了才导致的卡白果呢？

**Comment by ParrotXray** [comment]
> 请大佬帮忙看看
> 
> 使用最新OC0.9.0，安装Mac OS 13.3 Ventura-做如下安装测试：
> 
> 
> 
> 本人配置： B85M D3H (rev1.2版本) - E3-1231V3 - BCM943602CS - RX580
> 
> 1.Bois刷回F12版本，但启动进入Bois未发现CFG Lock, 无法设置关闭； 其他Bios参数已经按照提示设置好。
> 
> 
> 
> 2.直接使用解压的EFI, 删除EFI/OC/ACPI内的文件，使用B85M-D3H ACPI文件，OC启用，设备型号OC中联网选择MacPro7.1，保存，安装时卡在【MacOS Ventura将安装在磁盘“OS”上----剩余大约12分钟】左右卡死重启。
> 
> 
> 
> 3.直接使用解压的EFI, 未使用B85M-D3H ACPI内容，设备型号OC中联网选择MacPro7.1， 安装时亦卡在【MacOS Ventura将安装在磁盘“OS”上----剩余大约12分钟】左右卡死重启。
> 
> 
> 
> EFI引导提示：
> 
> 
> 
> #【EB.LD.LF|IND】(“(null string)"> ("1*)
> 
> #【CEB.B.SBS|SZ】 723512
> 
> #【CEB|B:SHA 】(Gaaf054766771d2h08ff011eb600c90c161d9285)
> 
> #【LEB.WL.PWLFNV11】 Err (0xE) <- RT.GV wake-fallure 7C436110-AB2R-4BBB-ABBO-FE41995C9FB2
> 
> #【CEB.ML.DTI11 Err(0xE) <- EB.WL.PWLFNV
> 
> #【CEB.WL.PWLFRTC I NONE1
> 
> #【LEB.WL.DTI1】 Err(OxE) <- EB.WL.PULFRTC
> 
> #【EB.LD.LKCID]】("System)LibraryWernelCollections\BootKernelExtensions.kc.development">
> 
> #【HEB.LD.OFS|OPEN1】 Err (®xE) ("System) WLibrary) VernelCollections\ \BootKernelExtensions.kc.development">
> 
> #【EB.LD.LKCIR.2】 ("System\Llbrary\ KernelCollections\BootKernelExtensions.kc">
> 
> xxxxx
> 
> -----之后滚条进入安装界面
> 
> 
> 
> 安装日志错误提示(剩余大约12分钟卡死重启前的提示)：
> 
> -------xxx   Syncing extracted data to disk
> 
> 
> 
> 请问一下，我是不是哪里配置出错了才导致的卡白果呢？

您是安裝哪個版本的，可以的話也試看看以前的引導文件

**Comment by Znano5696** [comment]
安裝的是OSX 13.3, 使用的是OC 0.9.0,  之後相繼測試了OC 0.85, 0.85Dev, 和0.87版本，也同樣在安裝界面剩余大约12分钟卡死重启，不知道出了什麼問題。

我想咨詢一下，您這邊bois的CFG Lock是怎麼解鎖的呢？我刷了B85M D3H 的F12版本bois, 但是未看到該CFG Lock設置選項

**Comment by Znano5696** [comment]
> 
安裝的是OSX 13.3, 使用的是OC 0.9.0, 之後相繼測試了OC 0.85, 0.85Dev, 和0.87版本，也同樣在安裝界面剩余大约12分钟卡死重启，不知道出了什麼問題。

我想咨詢一下，您這邊bois的CFG Lock是怎麼解鎖的呢？我刷了B85M D3H 的F12版本bois, 但是未看到該CFG Lock設置選項

**Comment by ParrotXray** [comment]
> 安裝的是OSX 13.3, 使用的是OC 0.9.0, 之後相繼測試了OC 0.85, 0.85Dev, 和0.87版本，也同樣在安裝界面剩余大约12分钟卡死重启，不知道出了什麼問題。
> 
> 我想咨詢一下，您這邊bois的CFG Lock是怎麼解鎖的呢？我刷了B85M D3H 的F12版本bois, 但是未看到該CFG Lock設置選項

EFI引导提示：

#【EB.LD.LF|IND】(“(null string)"> ("1*)

#【CEB.B.SBS|SZ】 723512

#【CEB|B:SHA 】(Gaaf054766771d2h08ff011eb600c90c161d9285)

#【LEB.WL.PWLFNV11】 Err (0xE) <- RT.GV wake-fallure 7C436110-AB2R-4BBB-ABBO-FE41995C9FB2

#【CEB.ML.DTI11 Err(0xE) <- EB.WL.PWLFNV

#【CEB.WL.PWLFRTC I NONE1

#【LEB.WL.DTI1】 Err(OxE) <- EB.WL.PULFRTC

#【EB.LD.LKCID]】("System)LibraryWernelCollections\BootKernelExtensions.kc.development">

#【HEB.LD.OFS|OPEN1】 Err (®xE) ("System) WLibrary) VernelCollections\ \BootKernelExtensions.kc.development">

#【EB.LD.LKCIR.2】 ("System\Llbrary\ KernelCollections\BootKernelExtensions.kc">

上段應該為第一階段的跑碼，只要能到第二階段跑完進入安裝畫面基本不用管

CFG lock 預設解鎖的

你試一下這個，這是我當前正使用的0.9.1版的，序號都弄好了
[EFI.zip](https://github.com/ParrotXray/GA-B85M-D3H-Haswell-Hackintosh/files/11303573/EFI.zip)

**Comment by Znano5696** [comment]
> > 安裝的是OSX 13.3, 使用的是OC 0.9.0, 之後相繼測試了OC 0.85, 0.85Dev, 和0.87版本，也同樣在安裝界面剩余大约12分钟卡死重启，不知道出了什麼問題。
> > 我想咨詢一下，您這邊bois的CFG Lock是怎麼解鎖的呢？我刷了B85M D3H 的F12版本bois, 但是未看到該CFG Lock設置選項
> 
> EFI引导提示：
> 
> #【EB.LD.LF|IND】(“(null string)"> ("1*)
> 
> #【CEB.B.SBS|SZ】 723512
> 
> #【CEB|B:SHA 】(Gaaf054766771d2h08ff011eb600c90c161d9285)
> 
> #【LEB.WL.PWLFNV11】 Err (0xE) <- RT.GV wake-fallure 7C436110-AB2R-4BBB-ABBO-FE41995C9FB2
> 
> #【CEB.ML.DTI11 Err(0xE) <- EB.WL.PWLFNV
> 
> #【CEB.WL.PWLFRTC I NONE1
> 
> #【LEB.WL.DTI1】 Err(OxE) <- EB.WL.PULFRTC
> 
> #【EB.LD.LKCID]】("System)LibraryWernelCollections\BootKernelExtensions.kc.development">
> 
> #【HEB.LD.OFS|OPEN1】 Err (®xE) ("System) WLibrary) VernelCollections\ \BootKernelExtensions.kc.development">
> 
> #【EB.LD.LKCIR.2】 ("System\Llbrary\ KernelCollections\BootKernelExtensions.kc">
> 
> 上段應該為第一階段的跑碼，只要能到第二階段跑完進入安裝畫面基本不用管
> 
> CFG lock 預設解鎖的
> 
> 你試一下這個，這是我當前正使用的0.9.1版的，序號都弄好了 [EFI.zip](https://github.com/ParrotXray/GA-B85M-D3H-Haswell-Hackintosh/files/11303573/EFI.zip)

我測試了這個版本的引導，還是出現了同樣的EB報錯，我參考了遠景論壇的帖子，測試了其他的引導，也無法安裝成功。依舊非常感謝您提供的幫助，我等過段時間再來研究出現的報錯吧，非常感謝您提供的幫助。
